name: Main Push
on:
  schedule:
    - cron: "0 13 * * 1"
  push:
    branches:
      - main
    paths:
      - docker-images/**
jobs:
  publish-to-staging:
    name: Publish (Staging)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.BASE_REGION }}
          role-to-assume: "arn:aws:iam::${{ secrets.STAGING_ACCOUNT_ID }}:role/ActionsRole"
          mask-aws-account-id: true

      - name: Build and push
        run: |
          cd common
          npm ci
          SSM_PARAMETER="$(node - <<<"console.log((await import('./dist/index.js')).SSMParameters.ImageRepositories.NS2Server.Name)")"

          cd ../docker-images/ns2server
          IMAGE_NAME=$(aws ssm get-parameter --name "$SSM_PARAMETER" | jq -r '.Parameter.Value')
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_NAME:latest
          docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$IMAGE_NAME:latest
        env:
          REGION: ${{ vars.BASE_REGION }}
          ACCOUNT_ID: ${{ secrets.STAGING_ACCOUNT_ID }}
